export const PERSONAL_ACCOUNT_UPDATED = "PERSONAL_ACCOUNT_UPDATED";
export const PERSONAL_ACCOUNT_REMOVED = "PERSONAL_ACCOUNT_REMOVED";
export const PERSONAL_ACCOUNTS_FETCH_SUCCESS = "PERSONAL_ACCOUNTS_FETCH_SUCCESS";
