export const PERSONAL_ACCOUNT_REMOVED = "PERSONAL_ACCOUNT_REMOVED";
export const PERSONAL_ACCOUNT_UPDATED = "PERSONAL_ACCOUNT_UPDATED";
export const PERSONAL_ACCOUNT_SHARED = "PERSONAL_ACCOUNT_SHARED";
export const PERSONAL_ACCOUNT_SHARING_REMOVED = "PERSONAL_ACCOUNT_SHARING_REMOVED";
export const PERSONAL_ACCOUNT_PAGINATION_PAGE_CHANGED = "PERSONAL_ACCOUNT_PAGINATION_PAGE_CHANGED";
export const PERSONAL_ACCOUNT_SEARCH_CHANGED = "PERSONAL_ACCOUNT_SEARCH_CHANGED";
export const PERSONAL_ACCOUNTS_FETCH_SUCCESS = "PERSONAL_ACCOUNTS_FETCH_SUCCESS";
