version: "2.4"

services:

  configuration-service:
    ports:
      - "8088:8088"
      - "5005:5005"
    build:
      context: ./configurationService
      dockerfile: docker/DockerfileDev

  discovery-service:
    ports:
      - "8761:8761"
      - "5006:5006"
    build:
      context: ./discoveryService
      dockerfile: docker/DockerfileDev

  gateway-service:
    ports:
      - "8887:8887"
      - "5007:5007"
    build:
      context: ./gatewayService
      dockerfile: docker/DockerfileDev

  authorization-service:
    ports:
      - "8888:8888"
      - "5008:5008"
    build:
      context: ./authorizationService
      dockerfile: docker/DockerfileDev

  auth-redis:
    ports:
      - "5001:6379"

  auth-postgres:
    ports:
      - "5003:5432"

  personal-accounts-postgres:
    ports:
      - "5002:5432"

  personal-accounts-redis:
    ports:
      - "5004:6379"

  personal-accounts-service:
    ports:
      - "8890:8890"
      - "5010:5010"
    build:
      context: ./personalAccountsService
      dockerfile: docker/DockerfileDev

  email-redis:
    ports:
      - "5009:6379"

  email-service:
    ports:
      - "8891:8891"
      - "5011:5011"
    build:
      context: ./emailService
      dockerfile: docker/DockerfileDev

  zookeeper1:
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka1:
    ports:
      - "9092:9092"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=DOCKER_LISTENER:PLAINTEXT
      - KAFKA_CFG_LISTENERS=DOCKER_LISTENER://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=DOCKER_LISTENER://kafka1:9092
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=DOCKER_LISTENER