version: "2.4"

services:

  configuration-service:
    ports:
      - "8088:8088"
      - "5005:5005"
    build:
      context: ./configurationService
      dockerfile: docker/Dockerfile
      target: debug

  discovery-service:
    ports:
      - "8761:8761"
      - "5006:5006"
    build:
      context: ./discoveryService
      dockerfile: docker/Dockerfile
      target: debug

  gateway-service:
    ports:
      - "8887:8887"
      - "5007:5007"
    build:
      context: ./gatewayService
      dockerfile: docker/Dockerfile
      target: debug

  authorization-service:
    ports:
      - "8888:8888"
      - "5008:5008"
    build:
      context: ./authorizationService
      dockerfile: docker/Dockerfile
      target: debug

  auth-redis:
    ports:
      - "5001:6379"

  auth-postgres:
    ports:
      - "5003:5432"

  personal-accounts-postgres:
    ports:
      - "5002:5432"

  personal-accounts-redis:
    ports:
      - "5004:6379"

  personal-accounts-service:
    ports:
      - "8890:8890"
      - "5010:5010"
    build:
      context: ./personalAccountsService
      dockerfile: docker/Dockerfile
      target: debug

  email-redis:
    ports:
      - "5009:6379"

  email-service:
    ports:
      - "8891:8891"
      - "5011:5011"
    build:
      context: ./emailService
      dockerfile: docker/Dockerfile
      target: debug

  zookeeper1:
    ports:
      - "2181:2181"

  kafka1:
    ports:
      - "9092:9092"