export const FOLDER_UPDATED = "FOLDER_UPDATED";
export const FOLDER_REMOVED = "FOLDER_REMOVED";
export const FOLDER_SELECTED = "FOLDER_SELECTED";
export const FOLDERS_FETCH_SUCCESS = "FOLDERS_FETCH_SUCCESS";
export const FOLDER_ACCOUNT_SIZE_INCREASED = "FOLDER_ACCOUNT_SIZE_INCREASED";
export const FOLDER_ACCOUNT_SIZE_DECREASED = "FOLDER_ACCOUNT_SIZE_DECREASED";