export const SHARINGS_FETCH_SUCCESS = "SHARINGS_FETCH_SUCCESS";
export const SHARING_SELECTED = "SHARING_SELECTED";
export const SHARING_ACCOUNT_SIZE_DECREASED = "SHARING_ACCOUNT_SIZE_DECREASED";
export const SHARING_ACCOUNT_SIZE_UPDATED = "SHARING_ACCOUNT_SIZE_UPDATED";